# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 65945607c9bb126705d1b121d731ffd83d80749b94eceb827aee8a7f00c3030c4313d623bd15a72946f26f78a571db7d03da6ba23751abc9f12e7cd10895d349

test:
  secret_key_base: f40e8ff7770211ae613ae29daf976ef680902a7800a55966edefd97e0972000d6a304a7439136425272b167dbba4aa8161d17c674b054fcb34ee682ae6683d85

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
